import keyMirror from 'key-mirror';

export default keyMirror({
    LOGIN: null,
    LOGOUT: null,

    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,

    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,

    SESSION_TOKEN_REQUEST: null,
    SESSION_TOKEN_SUCCESS: null,
    SESSION_TOKEN_FAILURE: null,

    DELETE_TOKEN_REQUEST: null,
    DELETE_TOKEN_SUCCESS: null,
    DELETE_TOKEN_FAILURE: null,

    SAVE_TOKEN_REQUEST: null,
    SAVE_TOKEN_SUCCESS: null,
    SAVE_TOKEN_FAILURE: null,

    GET_TOKEN_REQUEST: null,
    GET_TOKEN_SUCCESS: null,
    GET_TOKEN_FAILURE: null,

    SIGNUP_REQUEST: null,
    SIGNUP_SUCCESS: null,
    SIGNUP_FAILURE: null,

    RESET_PASSWORD_REQUEST: null,
    RESET_PASSWORD_SUCCESS: null,
    RESET_PASSWORD_FAILURE: null,

    GET_PROFILE_REQUEST: null,
    GET_PROFILE_SUCCESS: null,
    GET_PROFILE_FAILURE: null,

    UPDATE_PROFILE_REQUEST: null,
    UPDATE_PROFILE_SUCCESS: null,
    UPDATE_PROFILE_FAILURE: null,

    GET_VOUCH_REQUEST: null,
    GET_VOUCH_SUCCESS: null,
    GET_VOUCH_FAILURE: null,

    VOUCH_REQUEST: null,
    VOUCH_SUCCESS: null,
    VOUCH_FAILURE: null,

    VOUCHS_REQUEST: null,
    VOUCHS_SUCCESS: null,
    VOUCHS_FAILURE: null,

    VOUCHANDVOUCHS_REQUEST: null,
    VOUCHANDVOUCHS_SUCCESS: null,
    VOUCHANDVOUCHS_FAILURE: null,

    LINKMAN_REQUEST: null,
    LINKMAN_SUCCESS: null,
    LINKMAN_FAILURE: null,

    GET_MESSAGE_REQUEST:null,
    GET_MESSAGE_SUCCESS:null,
    GET_MESSAGE_FAILURE:null,

    READ_MESSAGE_REQUEST: null,
    READ_MESSAGE_SUCCESS: null,
    READ_MESSAGE_FAILURE: null,

    CURRENTSTOCK_REQUEST: null,
    CURRENTSTOCK_SUCCESS: null,
    CURRENTSTOCK_FAILURE: null,

    GET_USERFUNCS_REQUEST:null,
    GET_USERFUNCS_SUCCESS:null,
    GET_USERFUNCS_FAILURE:null,

    GET_REPORT_REQUEST:null,
    GET_REPORT_SUCCESS:null,
    GET_REPORT_FAILURE:null,

    GET_WHLISTS_REQUEST:null,
    GET_WHLISTS_SUCCESS:null,
    GET_WHLISTS_FAILURE:null,
    
    //
    CONNECTION_OPENED: null,
    CONNECTION_FAIL: null,
    CONNECTION_ERROR: null,

    RECEIVE_MESSAGE: null,
    //COMMENT_PROXY: null,

    // SEND_MESSAGE_REQUEST: null,
    // SEND_MESSAGE_SUCCESS: null,
    // SEND_MESSAGE_FAILURE: null
    GET_ENTERPRISE_INFO_REQUEST:null,
    GET_ENTERPRISE_INFO_SUCCESS:null,
    GET_ENTERPRISE_INFO_FAILURE:null,
    SAVE_ENTERPRISE_INFO_REQUEST:null,
    SAVE_ENTERPRISE_INFO_SUCCESS:null,
    SAVE_ENTERPRISE_INFO_FAILURE:null,
    GET_REMOTE_ENTERPRISE_INFO_REQUEST:null,
    GET_REMOTE_ENTERPRISE_INFO_SUCCESS:null,
    GET_REMOTE_ENTERPRISE_INFO_FAILURE:null
});